export type Country = { code: string; name: string };

export const COUNTRIES: Country[] = [
  { code: "RO", name: "România" },
  { code: "AF", name: "Afganistan" },
  { code: "ZA", name: "Africa de Sud" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "SA", name: "Arabia Saudită" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaidjan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BE", name: "Belgia" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BT", name: "Bhutan" },
  { code: "BY", name: "Belarus" },
  { code: "BO", name: "Bolivia" },
  { code: "BA", name: "Bosnia și Herțegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BR", name: "Brazilia" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "KH", name: "Cambodgia" },
  { code: "CM", name: "Camerun" },
  { code: "CA", name: "Canada" },
  { code: "CV", name: "Capul Verde" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CY", name: "Cipru" },
  { code: "CO", name: "Columbia" },
  { code: "KM", name: "Comore" },
  { code: "CG", name: "Congo" },
  { code: "CD", name: "Congo (RDC)" },
  { code: "KP", name: "Coreea de Nord" },
  { code: "KR", name: "Coreea de Sud" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Coasta de Fildeș" },
  { code: "HR", name: "Croația" },
  { code: "CU", name: "Cuba" },
  { code: "DK", name: "Danemarca" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egipt" },
  { code: "SV", name: "El Salvador" },
  { code: "CH", name: "Elveția" },
  { code: "AE", name: "Emiratele Arabe Unite" },
  { code: "ER", name: "Eritreea" },
  { code: "EE", name: "Estonia" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Etiopia" },
  { code: "FJ", name: "Fiji" },
  { code: "PH", name: "Filipine" },
  { code: "FI", name: "Finlanda" },
  { code: "FR", name: "Franța" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germania" },
  { code: "GH", name: "Ghana" },
  { code: "GR", name: "Grecia" },
  { code: "GD", name: "Grenada" },
  { code: "GT", name: "Guatemala" },
  { code: "GN", name: "Guineea" },
  { code: "GW", name: "Guineea-Bissau" },
  { code: "GQ", name: "Guineea Ecuatorială" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HN", name: "Honduras" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonezia" },
  { code: "JO", name: "Iordania" },
  { code: "IQ", name: "Irak" },
  { code: "IR", name: "Iran" },
  { code: "IE", name: "Irlanda" },
  { code: "IS", name: "Islanda" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italia" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japonia" },
  { code: "KZ", name: "Kazahstan" },
  { code: "KE", name: "Kenya" },
  { code: "KG", name: "Kârgâzstan" },
  { code: "KI", name: "Kiribati" },
  { code: "KW", name: "Kuweit" },
  { code: "LA", name: "Laos" },
  { code: "LS", name: "Lesotho" },
  { code: "LV", name: "Letonia" },
  { code: "LB", name: "Liban" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libia" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lituania" },
  { code: "LU", name: "Luxemburg" },
  { code: "MK", name: "Macedonia de Nord" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldive" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MA", name: "Maroc" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "MX", name: "Mexic" },
  { code: "FM", name: "Micronezia" },
  { code: "MD", name: "Republica Moldova" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Muntenegru" },
  { code: "MZ", name: "Mozambic" },
  { code: "MM", name: "Myanmar" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NZ", name: "Noua Zeelandă" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "NO", name: "Norvegia" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palau" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua Noua Guinee" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "PL", name: "Polonia" },
  { code: "PT", name: "Portugalia" },
  { code: "QA", name: "Qatar" },
  { code: "GB", name: "Regatul Unit" },
  { code: "CF", name: "Republica Centrafricană" },
  { code: "CZ", name: "Cehia" },
  { code: "DO", name: "Republica Dominicană" },
  { code: "RW", name: "Rwanda" },
  { code: "RU", name: "Rusia" },
  { code: "WS", name: "Samoa" },
  { code: "SM", name: "San Marino" },
  { code: "ST", name: "Sao Tome și Principe" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapore" },
  { code: "SY", name: "Siria" },
  { code: "SK", name: "Slovacia" },
  { code: "SI", name: "Slovenia" },
  { code: "SO", name: "Somalia" },
  { code: "ES", name: "Spania" },
  { code: "LK", name: "Sri Lanka" },
  { code: "US", name: "Statele Unite" },
  { code: "VA", name: "Vatican" },
  { code: "SD", name: "Sudan" },
  { code: "SS", name: "Sudanul de Sud" },
  { code: "SE", name: "Suedia" },
  { code: "SR", name: "Surinam" },
  { code: "TJ", name: "Tadjikistan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TH", name: "Thailanda" },
  { code: "TL", name: "Timorul de Est" },
  { code: "TG", name: "Togo" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad și Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turcia" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TV", name: "Tuvalu" },
  { code: "NL", name: "Țările de Jos" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ucraina" },
  { code: "HU", name: "Ungaria" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VU", name: "Vanuatu" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnam" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
  { code: "XK", name: "Kosovo" },
];

const BY_CODE = new Map(COUNTRIES.map((c) => [c.code, c]));
const BY_NAME = new Map(COUNTRIES.map((c) => [c.name.toLowerCase(), c]));

export function countryByCode(code: string) {
  return BY_CODE.get(code.toUpperCase());
}

export function countryByName(name: string) {
  return BY_NAME.get(name.trim().toLowerCase());
}

export function flagUrl(code: string, width = 40) {
  return `https://flagcdn.com/w${width}/${code.toLowerCase()}.png`;
}
