import type { Artist, Concert } from "./types";
import { artistKey } from "./utils";

function artist(name: string, extras: Partial<Artist> = {}): Artist {
  return {
    id: extras.id ?? artistKey(name),
    name,
    logoUrl: extras.logoUrl ?? null,
    thumbUrl: extras.thumbUrl ?? null,
    genre: extras.genre ?? null,
    country: extras.country ?? null,
    bio: extras.bio ?? null,
  };
}

const DEMO_ARTISTS: Artist[] = [
  artist("Metallica", { genre: "Thrash Metal", country: "SUA" }),
  artist("Phoenix", { genre: "Rock", country: "România" }),
  artist("Iron Maiden", { genre: "Heavy Metal", country: "Regatul Unit" }),
  artist("Depeche Mode", { genre: "Synth-pop", country: "Regatul Unit" }),
  artist("Arctic Monkeys", { genre: "Indie Rock", country: "Regatul Unit" }),
  artist("Radiohead", { genre: "Alternative Rock", country: "Regatul Unit" }),
  artist("Muse", { genre: "Alternative Rock", country: "Regatul Unit" }),
  artist("Coldplay", { genre: "Alternative Rock", country: "Regatul Unit" }),
  artist("The Weeknd", { genre: "R&B", country: "Canada" }),
  artist("Foo Fighters", { genre: "Rock", country: "SUA" }),
  artist("Florence + The Machine", { genre: "Indie Pop", country: "Regatul Unit" }),
  artist("Iris", { genre: "Rock", country: "România" }),
  artist("Golan", { genre: "Electropop", country: "România" }),
  artist("Cargo", { genre: "Hard Rock", country: "România" }),
  artist("Ghost", { genre: "Rock", country: "Suedia" }),
  artist("The Raven Age", { genre: "Metal", country: "Regatul Unit" }),
  artist("Travis Scott", { genre: "Hip Hop", country: "SUA" }),
];

function lineup(headliner: string, supports: string[] = []) {
  return [
    { artistId: artistKey(headliner), role: "headliner" as const },
    ...supports.map((name) => ({
      artistId: artistKey(name),
      role: "support" as const,
    })),
  ];
}

const DEMO_CONCERTS: Concert[] = [
  {
    id: "demo-phoenix-2014",
    date: "2014-12-06",
    venue: "Sala Palatului",
    city: "București",
    country: "România",
    countryCode: "RO",
    lineup: lineup("Phoenix"),
    notes: "Primul concert mare. Vocea lui Nicu Covaci încă umplea sala.",
    rating: 5,
    favorite: true,
    festival: false,
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "demo-radiohead-2016",
    date: "2016-08-12",
    venue: "Óbudai-sziget",
    city: "Budapesta",
    country: "Ungaria",
    countryCode: "HU",
    lineup: lineup("Radiohead"),
    notes: "Sziget, după-amiază toridă, A Moon Shaped Pool live.",
    rating: 5,
    favorite: true,
    festival: true,
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "demo-phoenix-2017",
    date: "2017-06-24",
    venue: "Arenele Romane",
    city: "București",
    country: "România",
    countryCode: "RO",
    lineup: lineup("Phoenix"),
    notes: "",
    rating: 4,
    favorite: false,
    festival: false,
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "demo-arctic-2018",
    date: "2018-08-10",
    venue: "Domeniul Știrbey",
    city: "Buftea",
    country: "România",
    countryCode: "RO",
    lineup: lineup("Arctic Monkeys"),
    notes: "Summer Well. Tranquility Base Hotel & Casino abia ieșise.",
    rating: 4,
    favorite: false,
    festival: true,
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "demo-metallica-2019",
    date: "2019-08-14",
    venue: "Romexpo",
    city: "București",
    country: "România",
    countryCode: "RO",
    lineup: lineup("Metallica", ["Ghost"]),
    notes: "WorldWired. Master of Puppets întreg.",
    rating: 5,
    favorite: true,
    festival: false,
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "demo-muse-2019",
    date: "2019-09-07",
    venue: "Romexpo",
    city: "București",
    country: "România",
    countryCode: "RO",
    lineup: lineup("Muse"),
    notes: "",
    rating: 4,
    favorite: false,
    festival: false,
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "demo-phoenix-2021",
    date: "2021-09-18",
    venue: "Arenele Romane",
    city: "București",
    country: "România",
    countryCode: "RO",
    lineup: lineup("Phoenix"),
    notes: "Primul show după pauza de pandemie.",
    rating: 5,
    favorite: false,
    festival: false,
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "demo-maiden-2022",
    date: "2022-05-29",
    venue: "Romexpo",
    city: "București",
    country: "România",
    countryCode: "RO",
    lineup: lineup("Iron Maiden", ["The Raven Age"]),
    notes: "Legacy of the Beast. Bruce încă zboară pe scenă.",
    rating: 5,
    favorite: true,
    festival: false,
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "demo-florence-2022",
    date: "2022-08-06",
    venue: "Cluj Arena",
    city: "Cluj-Napoca",
    country: "România",
    countryCode: "RO",
    lineup: lineup("Florence + The Machine"),
    notes: "Untold, noaptea principală.",
    rating: 5,
    favorite: true,
    festival: true,
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "demo-iris-2022",
    date: "2022-10-15",
    venue: "Sala Palatului",
    city: "București",
    country: "România",
    countryCode: "RO",
    lineup: lineup("Iris"),
    notes: "",
    rating: 4,
    favorite: false,
    festival: false,
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "demo-depeche-2023",
    date: "2023-06-10",
    venue: "Arena Națională",
    city: "București",
    country: "România",
    countryCode: "RO",
    lineup: lineup("Depeche Mode"),
    notes: "Memento Mori. Un show aproape liturgic.",
    rating: 5,
    favorite: true,
    festival: false,
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "demo-weeknd-2023",
    date: "2023-08-03",
    venue: "Cluj Arena",
    city: "Cluj-Napoca",
    country: "România",
    countryCode: "RO",
    lineup: lineup("The Weeknd"),
    notes: "Untold. After Hours până la Blinding Lights.",
    rating: 4,
    favorite: false,
    festival: true,
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "demo-golan-2024",
    date: "2024-03-22",
    venue: "Control Club",
    city: "București",
    country: "România",
    countryCode: "RO",
    lineup: lineup("Golan"),
    notes: "Club mic, sunet mare.",
    rating: 5,
    favorite: false,
    festival: false,
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "demo-coldplay-2024",
    date: "2024-06-15",
    venue: "Arena Națională",
    city: "București",
    country: "România",
    countryCode: "RO",
    lineup: lineup("Coldplay"),
    notes: "Music of the Spheres. Brățările LED au aprins tot stadionul.",
    rating: 5,
    favorite: true,
    festival: false,
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "demo-foo-2024",
    date: "2024-07-20",
    venue: "BT Arena",
    city: "Cluj-Napoca",
    country: "România",
    countryCode: "RO",
    lineup: lineup("Foo Fighters"),
    notes: "",
    rating: 4,
    favorite: false,
    festival: false,
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "demo-metallica-2025",
    date: "2025-05-17",
    venue: "Olympiastadion",
    city: "Berlin",
    country: "Germania",
    countryCode: "DE",
    lineup: lineup("Metallica"),
    notes: "M72. Al doilea Metallica, alt continent muzical.",
    rating: 5,
    favorite: true,
    festival: false,
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "demo-travis-2025",
    date: "2025-08-08",
    venue: "Cluj Arena",
    city: "Cluj-Napoca",
    country: "România",
    countryCode: "RO",
    lineup: lineup("Travis Scott"),
    notes: "Untold, cap de afiș.",
    rating: 3,
    favorite: false,
    festival: true,
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "demo-cargo-2026",
    date: "2026-04-12",
    venue: "Hard Rock Cafe",
    city: "București",
    country: "România",
    countryCode: "RO",
    lineup: lineup("Cargo"),
    notes: "Dacă pleci… live, aproape de scenă.",
    rating: 5,
    favorite: false,
    festival: false,
    createdAt: "2026-01-01T10:00:00.000Z",
  },
];

export function createDemoArchive(): {
  concerts: Concert[];
  artists: Record<string, Artist>;
} {
  const artists: Record<string, Artist> = {};
  for (const a of DEMO_ARTISTS) artists[a.id] = { ...a };
  return {
    concerts: DEMO_CONCERTS.map((c) => ({ ...c, lineup: c.lineup.map((l) => ({ ...l })) })),
    artists,
  };
}
